#!/bin/bash

		echo "25"
                add-apt-repository ppa:awn-testing 
                echo "35"
                apt-get update -y
		echo "40"
		apt-get -y --force-yes install avant-window-navigator-trunk
		echo "85"
		apt-get install -f -y
		echo "100"

