#!/bin/bash

                sudo sh -c 'echo "deb http://archive.canonical.com/ubuntu lucid partner" >> /etc/apt/sources.list' 
                sudo sh -c 'echo "deb-src http://archive.canonical.com/ubuntu lucid partner" >> /etc/apt/sources.list' 
                sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu lucid main restricted universe multiverse" >> /etc/apt/sources.list' 
                sudo sh -c 'echo "deb-src http://archive.ubuntu.com/ubuntu lucid main restricted universe multiverse" >> /etc/apt/sources.list' 
                sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu lucid-updates main restricted universe multiverse" >> /etc/apt/sources.list'  
                sudo sh -c 'echo "deb-src http://archive.ubuntu.com/ubuntu lucid-updates main restricted universe multiverse" >> /etc/apt/sources.list' 
                sudo sh -c 'echo "deb http://archive.ubuntu.com/ubuntu lucid-backports main restricted universe multiverse" >> /etc/apt/sources.list' 
                sudo sh -c 'echo "deb-src http://archive.ubuntu.com/ubuntu lucid-backports main restricted universe multiverse" >> /etc/apt/sources.list'
                sudo sh -c 'echo "deb http://archive.canonical.com/ lucid partner" >> /etc/apt/sources.list'
                           sudo apt-get update -y
		           sudo apt-get -y upgrade
