#!/bin/bash

                sudo sh -c 'echo "deb http://ppa.launchpad.net/jason-scheunemann/ppa/ubuntu karmic main" >> /etc/apt/sources.list' 
                sudo sh -c 'echo "deb-src http://ppa.launchpad.net/jason-scheunemann/ppa/ubuntu karmic main" >> /etc/apt/sources.list' 
                sudo wget -q 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x932062C9CD30EE56' -O - | sudo apt-key add 
                sudo apt-get update -y
		sudo apt-get -y upgrade
